version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app1:
    build:
      context: ./01
    ports:
      - "8080:8080"
    networks:
      - app-network

  app2:
    build:
      context: ./02
    ports:
      - "8081:8081"
    networks:
      - app-network

  app3:
    build:
      context: ./03
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - postgres
    command: ["/usr/local/bin/wait-for-it", "postgres:5432", "--timeout=30", "--strict", "--", "./app3"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local